## These functions are used to create, cache, and call a matrix and it's inverse. This functionality is more efficient than repetitively performing these operations, particularly since the matrix inverse function can be computationally intensive

## This function generates a matrix (as an object) and can also cache it's inverse

makeCacheMatrix <- function(x = matrix()) {
  inv <- NULL
  set <- function(y) {
    x <<- y
    inv <<- NULL
  }
  get <- function() x
  setInverse <- function(inverse) inv <<- inverse
  getInverse <- function() inv
  list(set = set,
       get = get,
       setInverse = setInverse,
       getInverse = getInverse)
}

## This function will generate the inverse of the matrix generated by the function "makeCacheMatrix", or will call the inverse from the cache if it is stored there
cacheSolve <- function(x, ...) {
  inv <- x$getInverse()
  if (!is.null(inv)) {
    message("getting cached data")
    return(inv)
  }
  mat <- x$get()
  inv <- solve(mat, ...)
  x$setInverse(inv)
  inv
}
